# Generated by Django 3.0.3 on 2020-03-23 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('youself', '0005_auto_20200322_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('avancement', models.TextField(blank=True)),
                ('lien_depot', models.URLField(blank=True)),
                ('phase', models.CharField(choices=[('1', 'non precisé'), ('2', 'rédaction de plan'), ('3', 'prototype'), ('4', 'phase de test'), ('4', 'phase de commercialisation')], default='-', max_length=100)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youself.Domaine')),
                ('porteurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youself.Utilisateur')),
            ],
        ),
    ]
