# Generated by Django 3.0.3 on 2020-03-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youproj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='phase',
            field=models.CharField(choices=[('0', 'non precisé'), ('1', 'idée'), ('2', 'rédaction de plan'), ('3', 'prototype'), ('4', 'phase de test'), ('4', 'phase de commercialisation')], default='-', max_length=100),
        ),
    ]
