# Generated by Django 3.0.3 on 2020-04-12 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('youself', '0005_auto_20200322_1705'),
        ('youproj', '0005_projet_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='somme_besoin_actuelle',
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etoile', models.IntegerField()),
                ('projet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='youproj.Projet')),
                ('suiveurs', models.ManyToManyField(related_name='projet_suivi', to='youself.Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youself.Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('somme_investi', models.IntegerField()),
                ('somme_requise', models.IntegerField()),
                ('somme_depense', models.IntegerField()),
                ('projet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='youproj.Projet')),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='equipe',
            field=models.ManyToManyField(blank=True, to='youproj.Role'),
        ),
    ]
