# Generated by Django 3.0.3 on 2020-04-15 11:19

from django.db import migrations, models
import django.db.models.deletion
import youproj.models


class Migration(migrations.Migration):
    dependencies = [
        ('youproj', '0006_auto_20200412_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mediatisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(help_text=youproj.models.Mediatisation.helpText,
                                          upload_to=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                                         to='youproj.Projet'))),
                ('projet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='youproj.Projet')),
            ],
        ),
    ]
