# Generated by Django 3.0.3 on 2020-03-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youself', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='competences',
            field=models.ManyToManyField(blank=True, to='youself.Competence'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='domaine',
            field=models.ManyToManyField(blank=True, to='youself.Domaine'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='img_url',
            field=models.ImageField(blank=True, upload_to='', verbose_name='photo de profile'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='pays',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
