# Generated by Django 3.0.3 on 2020-03-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youself', '0004_auto_20200321_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_naissance',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='img_url',
            field=models.ImageField(blank=True, default='profile/default-img.png', upload_to='profile/', verbose_name='photo de profile'),
        ),
    ]
